"""FastAPI surface.

Phase 6: switches the primary submission endpoint to accept a typed
:class:`IntakePayload` instead of a free-form JSON string. The OpenAPI
schema auto-generated by FastAPI now describes every intake field, so the
client can codegen its TypeScript types from ``/openapi.json``.

The legacy multipart endpoint is preserved for backwards compatibility
with the Phase-2 client; new clients should use ``/api/v1/submit``.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import List, Optional

import uvicorn
from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from src.assembly.mailing_packager import MailingPackager
from src.intake.intake_schema import IntakePayload
from src.intake.mcq_router import MCQRouter
from src.intake.ocr_parser import DocumentParser
from src.orchestrator.engine import TaxEngine

logger = logging.getLogger(__name__)


class TaxProcessResponse(BaseModel):
    """Top-level API response."""

    status: str = Field(description="'success' or 'error'.")
    tax_year: int
    federal_refund_or_owed: float = Field(
        description="Positive = owes IRS; negative = federal refund due."
    )
    ny_refund_or_owed: float = Field(
        default=0.0,
        description="NY positive = owes NY DTF; negative = NY refund.",
    )
    fica_refund_amount: float = Field(
        default=0.0, description="Total Form 843 FICA refund amount (Ssec + Medicare)."
    )
    forms_required: List[str] = Field(default_factory=list)
    completed_layers: List[str] = Field(default_factory=list)
    generated_form_outputs: List[str] = Field(
        default_factory=list,
        description="Paths to per-form filled PDFs or field-map JSONs.",
    )
    federal_packet_path: Optional[str] = None
    ny_packet_path: Optional[str] = None
    fica_packet_path: Optional[str] = None
    requires_human_review: List[str] = Field(
        default_factory=list,
        description=(
            "Reasons a CPA must review the return before filing. Non-empty "
            "when a validator or LLM confidence check flagged something. "
            "Pass force_assembly=True on a subsequent call to override after review."
        ),
    )
    narrative_sections: dict = Field(
        default_factory=dict,
        description=(
            "Plain-English narrative sections keyed by section title. "
            "Each value is a human-readable explanation of that portion of the return. "
            "Empty dict when narrative generation is not available."
        ),
    )


app = FastAPI(
    title="QuadTax NRA Tax Engine API",
    version="0.4.0",
    description=(
        "Production NRA tax return engine. Accepts intake fields and "
        "OCR'd document text; returns refund/owed amounts and paths to "
        "generated forms and Pub-519-Ch-8-ordered mailing packets."
    ),
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://127.0.0.1:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Modern endpoint: typed JSON payload
# ---------------------------------------------------------------------------


class SubmitRequest(BaseModel):
    """Inputs to ``POST /api/v1/submit``."""

    intake: IntakePayload
    i94_ocr_text: str = ""
    w2_ocr_texts: List[str] = Field(default_factory=list)
    form_1042s_ocr_texts: List[str] = Field(default_factory=list)
    output_dir: str = Field(default="outputs", description="Directory to write packets into.")
    force_assembly: bool = Field(
        default=False,
        description=(
            "When True the engine bypasses the human-review gate. The caller "
            "is acknowledging every reason previously surfaced in "
            "``requires_human_review``. Default False — first request returns "
            "the review list without producing forms."
        ),
    )


@app.get("/api/v1/healthz", tags=["meta"])
def healthz() -> dict:
    return {"status": "ok"}


@app.post("/api/v1/submit", response_model=TaxProcessResponse, tags=["tax"])
def submit(request: SubmitRequest) -> TaxProcessResponse:
    """Run the full L1-L9 pipeline against a typed intake payload."""
    router = MCQRouter()
    mcq_dict = router.to_mcq_answers(request.intake)

    # Pre-seed identity so Phase-3 add-ons (AMT, ITIN, Form 2210) read the
    # right values when they run inside run_full_pipeline().
    seeded_state = router.populate_state(request.intake)

    engine = TaxEngine(force_assembly=request.force_assembly)
    try:
        generated_forms, state = engine.run_full_pipeline(
            i94_ocr_text=request.i94_ocr_text,
            w2_ocr_texts=request.w2_ocr_texts,
            form_1042s_ocr_texts=request.form_1042s_ocr_texts,
            mcq_answers=mcq_dict,
            initial_state=seeded_state,
        )
    except Exception as exc:  # noqa: BLE001
        logger.exception("Pipeline failure")
        raise HTTPException(status_code=500, detail=str(exc)) from exc

    # Build mailing packets from whatever the populator wrote into outputs/.
    packager = MailingPackager(tax_year=state.tax_year)
    package = packager.assemble(
        state,
        forms_dir=Path("outputs"),
        output_dir=Path(request.output_dir),
    )

    from src.narrative.generator import NarrativeGenerator
    narrative = NarrativeGenerator().generate_sections(state)

    fica_total = (
        state.fica.incorrect_ss_withheld + state.fica.incorrect_medicare_withheld
    )
    return TaxProcessResponse(
        status="success",
        tax_year=state.tax_year,
        federal_refund_or_owed=float(state.tax.refund_or_owed),
        ny_refund_or_owed=float(state.ny.ny_refund_or_owed),
        fica_refund_amount=float(fica_total),
        forms_required=list(state.forms_required),
        completed_layers=list(state.completed_layers),
        generated_form_outputs=list(generated_forms),
        federal_packet_path=package.federal.pdf_output or package.federal.json_output,
        ny_packet_path=(
            package.ny.pdf_output or package.ny.json_output if package.ny else None
        ),
        fica_packet_path=(
            package.fica_843.pdf_output or package.fica_843.json_output
            if package.fica_843
            else None
        ),
        requires_human_review=list(state.requires_human_review),
        narrative_sections=narrative,
    )


# ---------------------------------------------------------------------------
# Legacy multipart endpoint (Phase-2 client)
# ---------------------------------------------------------------------------


@app.post(
    "/api/v1/upload-and-process",
    response_model=TaxProcessResponse,
    tags=["tax"],
    deprecated=True,
)
async def upload_and_process_endpoint(
    i94_file: UploadFile = File(...),
    w2_files: List[UploadFile] = File(default=[]),
    form_1042s_files: List[UploadFile] = File(default=[]),
    mcq_answers_json: str = Form(...),
) -> TaxProcessResponse:
    """Legacy multipart endpoint preserved for the Phase-2 client.

    New clients should use ``POST /api/v1/submit`` with the typed
    :class:`SubmitRequest` body.
    """
    try:
        mcq_answers = json.loads(mcq_answers_json)
        parser = DocumentParser()

        i94_bytes = await i94_file.read()
        i94_ocr_text = parser.parse_file(i94_bytes, i94_file.filename or "i94.pdf")

        w2_ocr_texts = []
        for w2 in w2_files:
            w2_bytes = await w2.read()
            w2_ocr_texts.append(parser.parse_file(w2_bytes, w2.filename or "w2.pdf"))

        form_1042s_ocr_texts = []
        for f1042s in form_1042s_files:
            f1042s_bytes = await f1042s.read()
            form_1042s_ocr_texts.append(
                parser.parse_file(f1042s_bytes, f1042s.filename or "1042s.pdf")
            )

        engine = TaxEngine()
        _generated, final_state = engine.run_full_pipeline(
            i94_ocr_text=i94_ocr_text,
            w2_ocr_texts=w2_ocr_texts,
            form_1042s_ocr_texts=form_1042s_ocr_texts,
            mcq_answers=mcq_answers,
        )
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(status_code=500, detail=str(exc)) from exc

    fica_total = (
        final_state.fica.incorrect_ss_withheld + final_state.fica.incorrect_medicare_withheld
    )
    return TaxProcessResponse(
        status="success",
        tax_year=final_state.tax_year,
        federal_refund_or_owed=float(final_state.tax.refund_or_owed),
        ny_refund_or_owed=float(final_state.ny.ny_refund_or_owed),
        fica_refund_amount=float(fica_total),
        forms_required=list(final_state.forms_required),
        completed_layers=list(final_state.completed_layers),
        generated_form_outputs=list(_generated),
        narrative_sections={},
    )


if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
