/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/ocr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Extract Documents
         * @description Extract structured fields from uploaded tax documents using OCR + LLM.
         */
        post: operations["extract_documents_api_v1_ocr_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_api_v1_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit
         * @description Run the full L1-L9 pipeline against a typed intake payload.
         */
        post: operations["submit_api_v1_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/packet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Packet
         * @description Serve a generated packet file. Only allows files under outputs/ directory.
         */
        get: operations["download_packet_api_v1_packet_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_extract_documents_api_v1_ocr_post */
        Body_extract_documents_api_v1_ocr_post: {
            /**
             * Tax Year
             * @default 2025
             */
            tax_year: number;
            /** I94 File */
            i94_file?: string | null;
            /**
             * W2 Files
             * @default []
             */
            w2_files: string[];
            /**
             * Form 1042S Files
             * @default []
             */
            form_1042s_files: string[];
            /**
             * Form 1099 Files
             * @default []
             */
            form_1099_files: string[];
        };
        /** Form1042SExtracted */
        Form1042SExtracted: {
            /**
             * Income Code
             * @default 0
             */
            income_code: number;
            /**
             * Gross Income
             * @default 0
             */
            gross_income: number;
            /**
             * Exemption Rate
             * @default 0
             */
            exemption_rate: number;
            /**
             * Exemption Code
             * @default
             */
            exemption_code: string;
            /**
             * Fed Withheld
             * @default 0
             */
            fed_withheld: number;
            /**
             * Chapter Indicator
             * @default 3
             */
            chapter_indicator: number;
            /**
             * Recipient Name
             * @default
             */
            recipient_name: string;
            /**
             * Withholding Agent Name
             * @default
             */
            withholding_agent_name: string;
        };
        /** Form1099Extracted */
        Form1099Extracted: {
            /**
             * Form Kind
             * @default
             */
            form_kind: string;
            /**
             * Gross Amount
             * @default 0
             */
            gross_amount: number;
            /**
             * Fed Withholding
             * @default 0
             */
            fed_withholding: number;
            /**
             * Payer Name
             * @default
             */
            payer_name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** I94Extracted */
        I94Extracted: {
            /**
             * Days Current Year
             * @default 0
             */
            days_current_year: number;
            /**
             * Days Minus 1
             * @default 0
             */
            days_minus_1: number;
            /**
             * Days Minus 2
             * @default 0
             */
            days_minus_2: number;
            /**
             * Latest Entry Date
             * @default
             */
            latest_entry_date: string;
            /**
             * Latest Class Of Admission
             * @default
             */
            latest_class_of_admission: string;
        };
        /**
         * IntakeBanking
         * @description Direct-deposit routing info for federal refunds.
         */
        IntakeBanking: {
            /**
             * Direct Deposit
             * @default false
             */
            direct_deposit: boolean;
            /**
             * Routing Number
             * @description 9-digit routing number.
             * @default
             */
            routing_number: string;
            /**
             * Account Number
             * @default
             */
            account_number: string;
            /**
             * Account Type
             * @default
             * @enum {string}
             */
            account_type: "checking" | "savings" | "";
        };
        /**
         * IntakeElections
         * @description Tax elections / disclosures the user has previously made.
         */
        IntakeElections: {
            /**
             * Section 6013G Election
             * @description §6013(g): NRA spouse of US person elected to be treated as resident.
             * @default false
             */
            section_6013g_election: boolean;
            /**
             * Section 6013H Election
             * @default false
             */
            section_6013h_election: boolean;
            /**
             * Section 871D Election
             * @description §871(d): real-property income treated as ECI.
             * @default false
             */
            section_871d_election: boolean;
            /**
             * Large Foreign Gifts Over 100K
             * @default false
             */
            large_foreign_gifts_over_100k: boolean;
            /**
             * Closer Connection Exception Claimed
             * @default false
             */
            closer_connection_exception_claimed: boolean;
        };
        /**
         * IntakeFICA
         * @description FICA-refund-claim context (Form 843 path).
         */
        IntakeFICA: {
            /**
             * Employer Attempted Refund
             * @description True if the employer was asked to refund FICA and refused.
             * @default false
             */
            employer_attempted_refund: boolean;
            /**
             * Has Form 8316
             * @description True if the employer-refusal Form 8316 is in hand.
             * @default false
             */
            has_form_8316: boolean;
            /**
             * Employer Name
             * @default
             */
            employer_name: string;
            /**
             * Employer Ein
             * @default
             */
            employer_ein: string;
        };
        /**
         * IntakeIdentity
         * @description Demographic, identifier, and address fields.
         */
        IntakeIdentity: {
            /**
             * First Name
             * @default
             */
            first_name: string;
            /**
             * Middle Initial
             * @default
             */
            middle_initial: string;
            /**
             * Last Name
             * @default
             */
            last_name: string;
            /**
             * Suffix
             * @default
             */
            suffix: string;
            /**
             * Date Of Birth
             * @description ISO date (YYYY-MM-DD).
             */
            date_of_birth?: string | null;
            /**
             * Ssn
             * @description 9 digits, no dashes. Empty if no SSN.
             * @default
             */
            ssn: string;
            /**
             * Itin
             * @description 9 digits, no dashes. Empty if no ITIN.
             * @default
             */
            itin: string;
            /**
             * Country Of Citizenship
             * @description ISO2 country code.
             * @default
             */
            country_of_citizenship: string;
            /**
             * Country Of Tax Residence
             * @description ISO2 country code.
             * @default
             */
            country_of_tax_residence: string;
            /**
             * Passport Number
             * @default
             */
            passport_number: string;
            /**
             * Passport Country
             * @description ISO2 country code.
             * @default
             */
            passport_country: string;
            /**
             * Us Address Line1
             * @default
             */
            us_address_line1: string;
            /**
             * Us Address Line2
             * @default
             */
            us_address_line2: string;
            /**
             * Us City
             * @default
             */
            us_city: string;
            /**
             * Us State
             * @default
             */
            us_state: string;
            /**
             * Us Zip
             * @default
             */
            us_zip: string;
            /**
             * Foreign Address Line1
             * @default
             */
            foreign_address_line1: string;
            /**
             * Foreign Address Line2
             * @default
             */
            foreign_address_line2: string;
            /**
             * Foreign City
             * @default
             */
            foreign_city: string;
            /**
             * Foreign State Province
             * @default
             */
            foreign_state_province: string;
            /**
             * Foreign Country
             * @default
             */
            foreign_country: string;
            /**
             * Foreign Postal Code
             * @default
             */
            foreign_postal_code: string;
            /**
             * Occupation
             * @default Student
             */
            occupation: string;
            /**
             * Daytime Phone
             * @default
             */
            daytime_phone: string;
            /**
             * Email
             * @default
             */
            email: string;
            /**
             * Filing Status
             * @default single
             * @enum {string}
             */
            filing_status: "single" | "mfs" | "qss";
            /**
             * Spouse First Name
             * @default
             */
            spouse_first_name: string;
            /**
             * Spouse Last Name
             * @default
             */
            spouse_last_name: string;
            /**
             * Spouse Ssn Or Itin
             * @default
             */
            spouse_ssn_or_itin: string;
        };
        /**
         * IntakeIncome
         * @description Income context the LLM-OCR alone can't supply.
         */
        IntakeIncome: {
            /**
             * Income Description
             * @description Free-text description of the filer's primary income source. Drives the L4 LLM treaty-category classifier.
             * @default
             */
            income_description: string;
            /**
             * Requires Services
             * @description True if the filer's grant required services (drives Code 16 routing).
             * @default false
             */
            requires_services: boolean;
            /**
             * Is Qualified Expense
             * @description True if a scholarship is for tuition/fees only (§117 exclusion).
             * @default false
             */
            is_qualified_expense: boolean;
            /**
             * Prior Year Treaty Claim Total
             * @description For Schedule OI Item L — prior-year treaty exempt amount.
             * @default 0
             */
            prior_year_treaty_claim_total: number;
        };
        /**
         * IntakeNYContext
         * @description NY-specific MCQ answers (set to None to skip the NY pipeline).
         */
        IntakeNYContext: {
            /**
             * Days In Ny
             * @default 0
             */
            days_in_ny: number;
            /**
             * Has Permanent Abode In Ny
             * @default false
             */
            has_permanent_abode_in_ny: boolean;
            /**
             * Abode Months In Year
             * @default 0
             */
            abode_months_in_year: number;
            /**
             * Is Student Dorm
             * @default true
             */
            is_student_dorm: boolean;
            /**
             * Domiciled In Ny
             * @default false
             */
            domiciled_in_ny: boolean;
            /**
             * Moved Into Ny Mid Year
             * @default false
             */
            moved_into_ny_mid_year: boolean;
            /**
             * Moved Out Of Ny Mid Year
             * @default false
             */
            moved_out_of_ny_mid_year: boolean;
            /**
             * Nyc Address
             * @default false
             */
            nyc_address: boolean;
            /**
             * Yonkers Address
             * @default false
             */
            yonkers_address: boolean;
            /**
             * Ny Work Days
             * @default 0
             */
            ny_work_days: number;
            /**
             * Total Work Days
             * @default 0
             */
            total_work_days: number;
            /**
             * Employer In Ny
             * @default true
             */
            employer_in_ny: boolean;
            /**
             * Institution 1042S In Ny
             * @default true
             */
            institution_1042s_in_ny: boolean;
        };
        /**
         * IntakePayload
         * @description Top-level intake payload — POSTed to /api/v1/submit.
         */
        IntakePayload: {
            identity: components["schemas"]["IntakeIdentity"];
            residency: components["schemas"]["IntakeResidency"];
            income: components["schemas"]["IntakeIncome"];
            /** @description Set to a populated object when the filer has any NY footprint. */
            ny?: components["schemas"]["IntakeNYContext"] | null;
            fica?: components["schemas"]["IntakeFICA"];
            banking?: components["schemas"]["IntakeBanking"];
            elections?: components["schemas"]["IntakeElections"];
        };
        /**
         * IntakeResidency
         * @description Residency / visa context. The OCR'd I-94 supplies the day counts.
         */
        IntakeResidency: {
            /**
             * Tax Year
             * @default 2025
             */
            tax_year: number;
            /**
             * Visa Type
             * @default F-1
             */
            visa_type: string;
            /**
             * Visa Subtype
             * @default student
             * @enum {string}
             */
            visa_subtype: "student" | "teacher_researcher" | "trainee" | "other";
            /**
             * First Us Arrival Year
             * @default 2024
             */
            first_us_arrival_year: number;
            /**
             * Prior Us Visa History
             * @description ISO date strings or 'YYYY' for each prior visa entry. Used to compute the cumulative 5-year exempt window.
             */
            prior_us_visa_history?: string[];
            /**
             * Prior Year Residency Status
             * @default none
             * @enum {string}
             */
            prior_year_residency_status: "nonresident_alien" | "resident_alien" | "none";
        };
        /** OcrResult */
        OcrResult: {
            i94?: components["schemas"]["I94Extracted"] | null;
            /** W2S */
            w2s?: components["schemas"]["W2Extracted"][];
            /** Form 1042S */
            form_1042s?: components["schemas"]["Form1042SExtracted"][];
            /** Form 1099S */
            form_1099s?: components["schemas"]["Form1099Extracted"][];
        };
        /**
         * SubmitRequest
         * @description Inputs to ``POST /api/v1/submit``.
         */
        SubmitRequest: {
            intake: components["schemas"]["IntakePayload"];
            /**
             * I94 Ocr Text
             * @default
             */
            i94_ocr_text: string;
            /** W2 Ocr Texts */
            w2_ocr_texts?: string[];
            /** Form 1042S Ocr Texts */
            form_1042s_ocr_texts?: string[];
            /**
             * Output Dir
             * @description Directory to write packets into.
             * @default outputs
             */
            output_dir: string;
            /**
             * Force Assembly
             * @description When True the engine bypasses the human-review gate. The caller is acknowledging every reason previously surfaced in ``requires_human_review``. Default False — first request returns the review list without producing forms.
             * @default false
             */
            force_assembly: boolean;
        };
        /**
         * TaxProcessResponse
         * @description Top-level API response.
         */
        TaxProcessResponse: {
            /**
             * Status
             * @description 'success' or 'error'.
             */
            status: string;
            /** Tax Year */
            tax_year: number;
            /**
             * Federal Refund Or Owed
             * @description Positive = owes IRS; negative = federal refund due.
             */
            federal_refund_or_owed: number;
            /**
             * Ny Refund Or Owed
             * @description NY positive = owes NY DTF; negative = NY refund.
             * @default 0
             */
            ny_refund_or_owed: number;
            /**
             * Fica Refund Amount
             * @description Total Form 843 FICA refund amount (Ssec + Medicare).
             * @default 0
             */
            fica_refund_amount: number;
            /** Forms Required */
            forms_required?: string[];
            /** Completed Layers */
            completed_layers?: string[];
            /**
             * Generated Form Outputs
             * @description Paths to per-form filled PDFs or field-map JSONs.
             */
            generated_form_outputs?: string[];
            /** Federal Packet Path */
            federal_packet_path?: string | null;
            /** Ny Packet Path */
            ny_packet_path?: string | null;
            /** Fica Packet Path */
            fica_packet_path?: string | null;
            /**
             * Requires Human Review
             * @description Reasons a CPA must review the return before filing. Non-empty when a validator or LLM confidence check flagged something. Pass force_assembly=True on a subsequent call to override after review.
             */
            requires_human_review?: string[];
            /**
             * Narrative Sections
             * @description Plain-English narrative sections keyed by section title. Each value is a human-readable explanation of that portion of the return. Empty dict when narrative generation is not available.
             */
            narrative_sections?: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** W2Extracted */
        W2Extracted: {
            /**
             * Box 1 Wages
             * @default 0
             */
            box_1_wages: number;
            /**
             * Box 2 Fed Withholding
             * @default 0
             */
            box_2_fed_withholding: number;
            /**
             * Box 3 Ss Wages
             * @default 0
             */
            box_3_ss_wages: number;
            /**
             * Box 4 Ss Withheld
             * @default 0
             */
            box_4_ss_withheld: number;
            /**
             * Box 5 Medicare Wages
             * @default 0
             */
            box_5_medicare_wages: number;
            /**
             * Box 6 Medicare Withheld
             * @default 0
             */
            box_6_medicare_withheld: number;
            /**
             * Box 17 State Income Tax
             * @default 0
             */
            box_17_state_income_tax: number;
            /**
             * Box 18 Local Wages
             * @default 0
             */
            box_18_local_wages: number;
            /**
             * Box 19 Local Income Tax
             * @default 0
             */
            box_19_local_income_tax: number;
            /**
             * Box 20 Locality Name
             * @default
             */
            box_20_locality_name: string;
            /**
             * Employer Name
             * @description Employer name from box c
             * @default
             */
            employer_name: string;
            /**
             * Employer Ein
             * @description Employer EIN from box b
             * @default
             */
            employer_ein: string;
            /**
             * Employee Name
             * @description Employee first+last from box e
             * @default
             */
            employee_name: string;
            /**
             * Employee Ssn Or Itin
             * @description SSN/ITIN from box a
             * @default
             */
            employee_ssn_or_itin: string;
            /**
             * Tax Year
             * @description Tax year on the W-2
             * @default 0
             */
            tax_year: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    extract_documents_api_v1_ocr_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_extract_documents_api_v1_ocr_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OcrResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_api_v1_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    submit_api_v1_submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxProcessResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_packet_api_v1_packet_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
